apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    #
    # Copied from nats docker project
    #

    # Client port of 4222 on all interfaces
    port: 4222

    # HTTP monitoring port
    monitor_port: 8222

    #
    # Unity custom settings
    #

    # This matches production config in
    # gitlab terraform-google-nats startup.sh
    max_payload: 5242880
