version: v2beta1
name: nats

pipelines:
  deploy:
    run: |-
      run_dependencies --all
      create_deployments --all

deployments:
  nats-configmap:
    kubectl:
      manifests:
        - ./configmap-nats.conf.yaml
  app:
    helm:
      releaseName: nats
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - name: nats
            image: nats
            volumeMounts:
              - containerPath: /nats.conf
                volume:
                  name: nats-config
                  subPath: nats.conf
                  readOnly: true
            command:
              - nats
              - --appendonly
              - "yes"
        service:
          ports:
            - name: client
              port: 4222
            - name: monitor
              port: 8222
        volumes:
          - name: nats-config
            configMap:
              name: nats-config
              
