version: v2beta1
name: bigtable-emulator

pipelines:
  deploy:
    run: |-
      run_dependencies --all
      create_deployments --all

deployments:
  app:
    helm:
      releaseName: bigtable-emulator
      upgradeArgs:
        - --set
        - useReleaseName=true
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - name: bigtable-emulator
            image: google/cloud-sdk:368.0.0
            command:
              - gcloud
              - beta
              - emulators
              - bigtable
              - start
              - --quiet
              - --project=local-development
              - --host-port
              - 0.0.0.0:9035
        service:
          ports:
            - port: 9035
