version: v2beta1
name: gcp-emulator

vars:
  PORT: 0
  GCP_GROUP:
    options:
      - pubsub
      - bigtable

pipelines:
  deploy:
    run: |-
      run_dependencies --all
      create_deployments --all

deployments:
  app:
    helm:
      releaseName: gcp-${GCP_GROUP}-emulator
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - name: gcp-${GCP_GROUP}-emulator
            image: google/cloud-sdk:368.0.0
            command:
              - gcloud
              - beta
              - emulators
              - ${GCP_GROUP}
              - start
              - --quiet
              - --project=local-development
              - --host-port
              - 0.0.0.0:${PORT}
        service:
          ports:
            - port: ${PORT}
